In [ ]:
## Numpy Array

In [2]:
import numpy as np
import time
import sys

l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size* array.itemsize)  # numpy is memory effective compared to python list

28000
4000


In [5]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# Python list
start = time.time()
result = [(x+y) for x,y in zip(l1, l2)]
print("Python list took: ", (time.time() - start)*1000)

start = time.time()
result = a1 + a2
print("Numpy list took: ", (time.time() - start)*1000)  # Numpy is also faster

Python list took:  197.99423217773438
Numpy list took:  22.503137588500977


## Two dimensions array

In [12]:
a = np.array([5, 6, 9])  # one dim array
a[0]

a = np.array([[1, 2], [3, 4], [5, 6]])  # one dim array
print("Number of dimensions: ", a.ndim)  # print the number of dimensions
print("Number of elements: ",a.size)  # total number of elements
print("Matrix dimensions: ", a.shape)  # matrix shape

Number of dimensions:  2
Number of elements:  6
Matrix dimensions:  (3, 2)


In [14]:
np.zeros((3,4))  # create a 3x4 zero matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))  # create a 3x4 ones matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(1, 5, 5)  # linear sequence of numbers

array([1., 2., 3., 4., 5.])

In [22]:
a.reshape(2,3)  # reshape a matrix/array
b = a.ravel()  # matrix to array

In [27]:
a.min()
a.min()
print("Sum of all elements: ", a.sum())
a.sum(axis=1)  # the sum of axis 1 elements
np.sqrt(a)  # square root
np.std(a)  # standard deviation

Sum of all elements:  21


1.707825127659933

In [30]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

a+b
a*b
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

## Slicing

In [41]:
a = np.array([6, 7, 8])
a[0:2]  # slicing the list
a[-1]

a = np.array([[6,7,8], [1,2,3], [9,3,2]])
a[1,2]
a[-1]  # last column
a[-1, 0:2]  # first two elements from last row
a[:, 1:3]  # all rows, second and third columns

array([[7, 8],
       [2, 3],
       [3, 2]])

## Elements manipulations

In [52]:
a = np.arange(6).reshape(3,2)
b = np.arange(6, 12).reshape(3, 2)
np.vstack((a,b))
np.hstack((a,b))


a = np.arange(30).reshape(2,15)
result = np.hsplit(a, 3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [55]:
a = np.arange(12).reshape(3,4)
b = a > 4  # return a bool matrix of numbers in a bigger than 4
b
a[b]  # extracts all elements > 4 from a
a[b] = -1  # replace all elements in a bigger then 4 with -1

array([ 5,  6,  7,  8,  9, 10, 11])

## Iterating

In [58]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [63]:
for x in np.nditer(a, order='F', flags=['external_loop']):  # print in Fortran order (by column, not by row)
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [66]:
for x in np.nditer(a, order='C', op_flags=['readwrite']):
    x[...]=x*x
a

array([[        0,         1,       256,      6561],
       [    65536,    390625,   1679616,   5764801],
       [ 16777216,  43046721, 100000000, 214358881]])

In [67]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 False
1 False
256 False
6561 False
65536 False
390625 True
1679616 True
5764801 True
16777216 True
43046721 True
100000000 True
214358881 True
